# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_preview',
            field=models.CharField(default='', max_length=250),
        ),
    ]
