# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_text_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text_preview',
            new_name='preview_text',
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
