# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170619_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='version',
        ),
        migrations.AddField(
            model_name='article',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
