# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20170706_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='revision',
            field=models.IntegerField(default=-1),
        ),
    ]
