# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text',
        ),
    ]
